services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: edensit139/gener:backend-dev
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - BASE_URL=http://localhost:5001
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: edensit139/gener:frontend-dev
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://localhost:5001
    depends_on:
      - backend