name: Build and Push Docker Images

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: edensit139
          password: 155246247

      - name: Build backend image
        run: |
          docker build -t edensit139/gener:backend-dev ./backend

      - name: Push backend image
        run: |
          docker push edensit139/gener:backend-dev

      - name: Build frontend image
        run: |
          docker build -t edensit139/gener:frontend-dev ./frontend

      - name: Push frontend image
        run: |
          docker push edensit139/gener:frontend-dev
